spring:
  datasource:
    url: jdbc:mysql://localhost:32768/sample3?createDatabaseIfNotExist=true
    username: root
    # password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
